//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;code&quot;:&quot;0&quot;,&quot;reason&quot;:&quot;ok! ! !&quot;,&quot;server_time&quot;:&quot;88&quot;,&quot;sid&quot;:&quot;14359957369642138526&quot;,&quot;slot_ad&quot;:[{&quot;ad&quot;:[{&quot;ad_action&quot;:{&quot;action&quot;:&quot;download&quot;},&quot;ad_content&quot;:{&quot;account_id&quot;:&quot;211566923&quot;,&quot;ad_pos_value&quot;:&quot;1&quot;,&quot;adm_fixed_ulk&quot;:&quot;&quot;,&quot;app_key&quot;:&quot;0&quot;,&quot;app_logo&quot;:&quot;https://huichuan-mc.sm.cn/211566908/25112838eb51d9c989a4ce86ec8e0c7864fb56.png&quot;,&quot;app_name&quot;:&quot;学而思网校&quot;,&quot;app_source&quot;:&quot;2&quot;,&quot;app_type&quot;:&quot;-1&quot;,&quot;author_id&quot;:&quot;&quot;,&quot;button_interaction_type&quot;:&quot;1&quot;,&quot;can_shake&quot;:&quot;8&quot;,&quot;category_id&quot;:&quot;0&quot;,&quot;category_name&quot;:&quot;&quot;,&quot;channel_id&quot;:&quot;&quot;,&quot;cid&quot;:&quot;338586&quot;,&quot;component_ids&quot;: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string adx_json {
            get {
                return ResourceManager.GetString("adx_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;110000&quot;,
        ///        &quot;province&quot;: &quot;北京市&quot;,
        ///        &quot;city&quot;: &quot;全部&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;110000&quot;,
        ///        &quot;province&quot;: &quot;北京市&quot;,
        ///        &quot;city&quot;: &quot;北京市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;120000&quot;,
        ///        &quot;province&quot;: &quot;天津市&quot;,
        ///        &quot;city&quot;: &quot;全部&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;120000&quot;,
        ///        &quot;province&quot;: &quot;天津市&quot;,
        ///        &quot;city&quot;: &quot;天津市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;130000&quot;,
        ///        &quot;province&quot;: &quot;河北省&quot;,
        ///        &quot;city&quot;: &quot;全部&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;130100&quot;,
        ///        &quot;prov [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string region_1 {
            get {
                return ResourceManager.GetString("region_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{
        ///		&quot;code&quot;: &quot;110000&quot;,
        ///		&quot;province&quot;: &quot;北京市&quot;,
        ///		&quot;city&quot;: &quot;北京&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;120000&quot;,
        ///		&quot;province&quot;: &quot;天津市&quot;,
        ///		&quot;city&quot;: &quot;天津&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130000&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;河北&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130100&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;石家庄&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130200&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;唐山&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130300&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;秦皇岛&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130400&quot;,
        ///		&quot;province&quot;: &quot;河北省&quot;,
        ///		&quot;city&quot;: &quot;邯郸&quot;
        ///	},
        ///	{
        ///		&quot;code&quot;: &quot;130500&quot;,
        ///		&quot;provin [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string region_2 {
            get {
                return ResourceManager.GetString("region_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;340800&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;安庆市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;340300&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;蚌埠市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;341600&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;亳州市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;341100&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;滁州市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;341200&quot;,
        ///        &quot;province&quot;: &quot;安徽省&quot;,
        ///        &quot;city&quot;: &quot;阜阳市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;340100&quot;,
        ///        &quot;p [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string region_3 {
            get {
                return ResourceManager.GetString("region_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;214&quot;,
        ///        &quot;province&quot;: &quot;北京市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;234&quot;,
        ///        &quot;province&quot;: &quot;天津市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;254&quot;,
        ///        &quot;province&quot;: &quot;河北省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;433&quot;,
        ///        &quot;province&quot;: &quot;山西省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;559&quot;,
        ///        &quot;province&quot;: &quot;内蒙古自治区&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;673&quot;,
        ///        &quot;province&quot;: &quot;辽宁省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;786&quot;,
        ///        &quot;province&quot;: &quot;吉林省&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;853&quot;,
        ///        &quot;prov [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string region_4_1 {
            get {
                return ResourceManager.GetString("region_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;code&quot;: &quot;215&quot;,
        ///        &quot;city&quot;: &quot;北京市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;235&quot;,
        ///        &quot;city&quot;: &quot;天津市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;255&quot;,
        ///        &quot;city&quot;: &quot;石家庄市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;279&quot;,
        ///        &quot;city&quot;: &quot;唐山市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;294&quot;,
        ///        &quot;city&quot;: &quot;秦皇岛市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;302&quot;,
        ///        &quot;city&quot;: &quot;邯郸市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;322&quot;,
        ///        &quot;city&quot;: &quot;邢台市&quot;
        ///    },
        ///    {
        ///        &quot;code&quot;: &quot;340&quot;,
        ///        &quot;city&quot;: &quot;保定市&quot;
        ///    },
        ///    {
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string region_4_2 {
            get {
                return ResourceManager.GetString("region_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///       &quot;code&quot;:&quot;120000&quot;,
        ///       &quot;name&quot;:&quot;天津&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;130000&quot;,
        ///       &quot;name&quot;:&quot;河北省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;140000&quot;,
        ///       &quot;name&quot;:&quot;山西省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;150000&quot;,
        ///       &quot;name&quot;:&quot;内蒙古自治区&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;210000&quot;,
        ///       &quot;name&quot;:&quot;辽宁省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;220000&quot;,
        ///       &quot;name&quot;:&quot;吉林省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;230000&quot;,
        ///       &quot;name&quot;:&quot;黑龙江省&quot;
        ///    },
        ///    {
        ///       &quot;code&quot;:&quot;310000&quot;,
        ///       &quot;name&quot;:&quot;上海&quot;
        ///    },
        ///    {
        ///       &quot;code [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string region_ipzan {
            get {
                return ResourceManager.GetString("region_ipzan", resourceCulture);
            }
        }
    }
}
