//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CefClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CefClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Object.defineProperty(window.screen,&quot;width&quot;,{get:function(){return 360;}});
        ///Object.defineProperty(window.screen,&quot;height&quot;,{get:function(){return 640;}});
        ///Object.defineProperty(window.screen,&quot;availHeight&quot;,{get:function(){return 360;}});
        ///Object.defineProperty(window.screen,&quot;availWidth&quot;,{get:function(){return 640;}}); 的本地化字符串。
        /// </summary>
        public static string js {
            get {
                return ResourceManager.GetString("js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;ua&quot;: &quot;Mozilla/5.0 (Linux; Android 12; CPH2471 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.155 Mobile Safari/537.36&quot;,
        ///  &quot;make&quot;: &quot;oppo&quot;,
        ///  &quot;model&quot;: &quot;CPH2471&quot;,
        ///  &quot;sw&quot;: &quot;720&quot;,
        ///  &quot;sh&quot;: &quot;1600&quot;,
        ///  &quot;osv&quot;: &quot;12&quot;
        ///} 的本地化字符串。
        /// </summary>
        public static string js_dev {
            get {
                return ResourceManager.GetString("js_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;huichuan&quot;: &quot;on&quot;,
        ///  &quot;abl&quot;: 50,
        ///  &quot;abln&quot;: 0,
        ///  &quot;yys&quot;: &quot;&quot;,
        ///  &quot;yys_dx&quot;: 0,
        ///  &quot;yys_lt&quot;: 0,
        ///  &quot;yys_yd&quot;: 0,
        ///  &quot;yysn&quot;: 0,
        ///  &quot;id&quot;: 12367,
        ///  &quot;admin&quot;: &quot;admin&quot;,
        ///  &quot;cef&quot;: 3,
        ///  &quot;title&quot;: &quot;搜狐+曝光&quot;,
        ///  &quot;type&quot;: &quot;刷UV&quot;,
        ///  &quot;client&quot;: 1,
        ///  &quot;referer&quot;: &quot;{\&quot;identifyid\&quot;:10}&quot;,
        ///  &quot;url&quot;: &quot;http://agn.aty.sohu.com/m&quot;,
        ///  &quot;url2&quot;: &quot;&quot;,
        ///  &quot;sleep&quot;: &quot;1-4&quot;,
        ///  &quot;uv&quot;: 20,
        ///  &quot;pv&quot;: 1,
        ///  &quot;param&quot;: &quot;&quot;,
        ///  &quot;address&quot;: &quot;全部&quot;,
        ///  &quot;click_rate&quot;: 0,
        ///  &quot;click_url&quot;: &quot;&quot;,
        ///  &quot;jstext&quot;: &quot;&quot;,
        ///  &quot;uv-sum&quot;: 0,
        ///  &quot;uv-click-num&quot;: 0,
        ///  &quot;uv-ios-num [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string js_task {
            get {
                return ResourceManager.GetString("js_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;code&quot;:&quot;0&quot;,&quot;reason&quot;:&quot;ok! ! !&quot;,&quot;server_time&quot;:&quot;88&quot;,&quot;sid&quot;:&quot;14359957369642138526&quot;,&quot;slot_ad&quot;:[{&quot;ad&quot;:[{&quot;ad_action&quot;:{&quot;action&quot;:&quot;download&quot;},&quot;ad_content&quot;:{&quot;account_id&quot;:&quot;211566923&quot;,&quot;ad_pos_value&quot;:&quot;1&quot;,&quot;adm_fixed_ulk&quot;:&quot;&quot;,&quot;app_key&quot;:&quot;0&quot;,&quot;app_logo&quot;:&quot;https://huichuan-mc.sm.cn/211566908/25112838eb51d9c989a4ce86ec8e0c7864fb56.png&quot;,&quot;app_name&quot;:&quot;学而思网校&quot;,&quot;app_source&quot;:&quot;2&quot;,&quot;app_type&quot;:&quot;-1&quot;,&quot;author_id&quot;:&quot;&quot;,&quot;button_interaction_type&quot;:&quot;1&quot;,&quot;can_shake&quot;:&quot;8&quot;,&quot;category_id&quot;:&quot;0&quot;,&quot;category_name&quot;:&quot;&quot;,&quot;channel_id&quot;:&quot;&quot;,&quot;cid&quot;:&quot;338586&quot;,&quot;component_ids&quot;: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string js_vast {
            get {
                return ResourceManager.GetString("js_vast", resourceCulture);
            }
        }
    }
}
